version: "3"

services:
  myapp:
    build:
      context: .
      args:
        FEATURE_SET: ${FEATURE_SET}
    ports:
      - "3000:3000"
    env_file:
      - /home/ubuntu/farmstack/.env #change the path accordingly
