version: '3'
volumes: 
  postgres-data:
  media:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$farmstack@!21
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '7000:5432'
    volumes:
      - "../postgres-new-07-22:/var/lib/postgresql/data"
    networks:
      - postgresql-network

  datahub:
    image: farmstack/datahub-ui:test
    container_name: datahub-ui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - postgresql-network

  datahub-be:
    image: farmstack/datahub-be:test
    container_name: datahub-be
    command: >
        sh -c "python manage.py makemigrations datahub participant accounts &&
        python manage.py migrate &&
        python manage.py loaddata db_scripts/userrole_fixture.yaml &&
        python manage.py loaddata db_scripts/initial_data.yaml && python manage.py runserver 0.0.0.0:8000" 
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../media/:/datahub/media
      - /home/ubuntu/datahub-api/core/utils.py:/datahub/core/utils.py
      - /home/ubuntu/datahub-api/core/settings.py:/datahub/core/settings.py

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $farmstack@!21
      POSTGRES_HOST_AUTH_METHOD: trust
      SENDGRID_API_KEY: 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
      EMAIL_HOST_USER: farmstack.dg@gmail.com
        # SENDGRID_API_KEY: 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
        # EMAIL_HOST_USER: varunramesh.07@gmail.com

      PORT: 7000
    links:
      - db:db
    networks:
      - postgresql-network

networks:
  postgresql-network:
    driver: bridge
